name: Deploy DCM User Guide

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Book
      uses: actions/checkout@v2
      with:
        path: book
    - name: Setting-up Book
      uses: actions/setup-node@v1
    - run: npm install gitbook-cli --global
    - run: gitbook install book
    - run: gitbook build book ../gh-pages
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        repository: Dronecode/camera-manager.dronecode.org
        path: gh-pages
    - run: ls -l gh-pages/master
      env:
        BUILD_DATE: echo `date`
    - name: Deploying book
      uses: EndBug/add-and-commit@v4
      with:
        #author_name: PX4BuildBot
        #author_email: px4buildbot@px4.io
        author_name: mrpollo
        author_email: mrpollo@gmail.com
        message: "gitbook build update ${{ env.BUILD_DATE }}"
        cwd: "gh-pages"
        add: "*"
      env:
        GITHUB_TOKEN: ${{ secrets.PX4BOT_TOKEN }}
        BUILD_DATE: echo `date`
